
services:
  postgresql:
    image: postgres:latest
    container_name: patient-service-db
    restart: always
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5000:5432"
    volumes:
      - ./patient-service-db:/var/lib/postgresql/data
    networks:
      - internal

  patient-service:
    build:
      context: ./patient-service
    container_name: patient-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=9001
    ports:
      - "4000:4000"
    networks:
      - internal
    depends_on:
      - postgresql


  billing-service:
    build:
      context: ./billing-service
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal

networks:
  internal:
